---
version: "3.7"

# This Docker composition file is used to build and test the container

secrets:
  aws_config:
    file: ./src/secrets/aws_config

services:
  scanner:
    # Run the container normally
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    image: cisagov/scanner
    init: true
    restart: "no"
    secrets:
      - source: aws_config
        target: aws_config
  redis:
    image: redis:alpine
