version: '3.2'

secrets:
  aws_config:
    file: ./secrets/aws/config
  aws_creds:
    file: ./secrets/aws/credentials

services:
  scan:
    image: 'dhub.ncats.dhs.gov:5001/scanner:latest'
    secrets:
      - source: aws_config
        target: aws_config
      - source: aws_creds
        target: aws_creds
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws_creds
      - AWS_PROFILE=default
    volumes:
      - /tmp:/home/scanner/shared
    dns:
     - 8.8.8.8
